/**
 * What `.ds-sync/pkg/` must contain, derived from the committed config.
 *
 * Both files this builds were hand-maintained gitignored copies of
 * `.design-sync/config.json` until 2026-09-02, and the barrel had already
 * drifted from the map it mirrors — its header claimed 18 components while it
 * exported 17. Deriving them removes the copy, and therefore the drift.
 *
 * Pure and dependency-free, in the shape scripts/changelog/rules.mjs uses, so
 * restage.test.mjs can assert the barrel names exactly `componentSrcMap`'s keys
 * with no `.ds-sync/` staged and no node_modules. The I/O is restage.mjs's.
 */

/** Thrown for a config this cannot build from; restage maps it onto exit 1. */
export class StagingError extends Error {}

/**
 * `pkg/package.json` — a stub whose only load-bearing field is `name`.
 *
 * package-build.mjs derives PKG_DIR by walking up from `--entry` to the first
 * package.json carrying a `name`. If this file is missing, PKG_DIR resolves to
 * `.ds-sync/` (whose package.json is the converter-deps stub `ds-sync-deps`),
 * and every cfg-relative path — cssEntry, srcDir, componentSrcMap — resolves
 * against the wrong root at once.
 */
export function packageJsonFor(cfg) {
  const name = cfg?.pkg;
  if (typeof name !== "string" || name === "") {
    throw new StagingError('config.json has no "pkg" name — pkg/package.json pins PKG_DIR and needs one');
  }
  return JSON.stringify({ name, version: "0.0.0", private: true }) + "\n";
}

/**
 * Map one componentSrcMap value onto the `@/…` specifier the barrel imports.
 *
 * Values are relative to `.design-sync/` (that is where the config lives and
 * how the driver resolves them); `@/` is the tsconfig alias for `cfg.srcDir`.
 * Both are string operations here so this stays filesystem-free — the paths are
 * config data, not something to stat.
 */
function specifierFor(name, srcPath, srcDir) {
  const norm = (p) => {
    const out = [];
    for (const seg of String(p).split(/[\\/]/)) {
      if (seg === "" || seg === ".") continue;
      if (seg === ".." && out.length && out[out.length - 1] !== "..") out.pop();
      else out.push(seg);
    }
    return out;
  };
  const root = norm(srcDir);
  const full = norm(srcPath);
  const under = root.every((seg, i) => full[i] === seg) && full.length > root.length;
  if (!under) {
    throw new StagingError(
      `componentSrcMap["${name}"] points outside cfg.srcDir — the barrel can only alias paths under ${srcDir}`
    );
  }
  return `@/${full.slice(root.length).join("/").replace(/\.[jt]sx?$/, "")}`;
}

/**
 * `pkg/entry.jsx` — the bundle barrel.
 *
 * One `export { … } from "@/…"` per source module, modules in the order the map
 * first names them and components in map order within each, so a config edit
 * produces a reviewable diff rather than a reshuffle.
 */
export function barrelFor(cfg) {
  const map = cfg?.componentSrcMap;
  if (!map || typeof map !== "object" || Object.keys(map).length === 0) {
    throw new StagingError("config.json has an empty componentSrcMap — there is nothing to export");
  }
  const srcDir = cfg.srcDir ?? "../../web/src";

  const byModule = new Map();
  for (const [name, srcPath] of Object.entries(map)) {
    const spec = specifierFor(name, srcPath, srcDir);
    if (!byModule.has(spec)) byModule.set(spec, []);
    byModule.get(spec).push(name);
  }

  const count = [...byModule.values()].reduce((n, names) => n + names.length, 0);
  const blocks = [...byModule.entries()].map(([spec, names]) =>
    names.length === 1
      ? `export { ${names[0]} } from "${spec}";\n`
      : `export {\n${names.map((n) => `  ${n},\n`).join("")}} from "${spec}";\n`
  );

  return {
    count,
    moduleCount: byModule.size,
    source:
      `// GENERATED by scripts/design-sync/restage.mjs from .design-sync/config.json.\n` +
      `// Do not edit — change componentSrcMap in the config and re-run restage.\n` +
      `//\n` +
      `// The design-sync bundle barrel: re-exports exactly the scoped design-system\n` +
      `// layer (${count} components) so the IIFE bundle stays bounded to these — not the\n` +
      `// whole Next.js app. \`@/\` and \`next/*\` imports resolve through the custom\n` +
      `// tsconfig paths (also generated by restage) at bundle time.\n\n` +
      blocks.join("\n"),
  };
}
