"""Generate ``jupyter_lite_config.json`` — the two things ``jupyter lite build`` must be told.

``PipliteAddon.piplite_urls``
    Pin the kernel to the ACTUAL built wheels so a qcsim version bump can never
    desync the pin. ``jupyter lite build`` bundles them into the generated
    piplite index, so the notebook bootstrap's ``piplite.install("qcsim")``
    resolves offline. (A settings ``overrides.json`` is NOT applied to lite
    plugin settings, so it cannot wire ``pipliteUrls``; PipliteAddon is the
    mechanism that works.)

``LiteBuildConfig.ignore_contents``
    jupyterlite-core's DEFAULT ignore list skips any path containing ``/lib/``
    (it assumes a build/env dir), which silently drops the curriculum's shared
    ``lib/`` package from the in-browser contents — every ``from lib import ...``
    cell then fails with ModuleNotFoundError. We override it with a curated
    subset of that default: ``/lib/`` REMOVED (so lib is indexed and importable)
    and ``/__pycache__/`` added, omitting the dynamic output_dir and
    jupyter-lite config-filename entries, which never appear under ``files/``.
    Re-check ``config.py`` ``_default_ignore_files`` on a jupyterlite-core bump.

Generated by a script rather than hand-maintained so the regex escaping is
correct and the output is deterministic. The committed
``jupyter_lite_config.json`` carries this output verbatim and CI asserts they
match (``git diff --exit-code``), so a version bump self-heals.

Usage (writes to stdout; build.sh redirects into the config file)::

    python write_lite_config.py <qcsim-wheel-name> <comm-wheel-name>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def build_config(qcsim_wheel: str, comm_wheel: str) -> dict:
    return {
        "LiteBuildConfig": {
            "output_dir": "../public/lab",
            "contents": ["files"],
            # Curated subset of jupyterlite-core's default ignore_contents (see
            # config.py _default_ignore_files): "/lib/" removed so the curriculum lib/
            # package is served to the kernel, "/__pycache__/" added; the dynamic
            # output_dir + jupyter-lite config-filename entries are omitted (none appear
            # under files/). Re-check _default_ignore_files on a jupyterlite-core bump.
            "ignore_contents": [
                r"/_build/",
                r"/\.cache/",
                r"/\.env",
                r"/\.git",
                r"/\.ipynb_checkpoints",
                r"/build/",
                r"/dist/",
                r"/envs/",
                r"/node_modules/",
                r"/__pycache__/",
                r"/overrides\.json",
                r"/untitled\..*",
                r"/Untitled\..*",
                r"/workspaces/",
                r"/venvs/",
                r"\.*doit\.db$",
                r"\.pyc$",
            ],
        },
        # qcsim (braket.* shim) + comm (the lab kernel's hard boot dependency, otherwise
        # fetched from pypi.org) bundled same-origin into the generated piplite index.
        "PipliteAddon": {
            "piplite_urls": [f"files/wheels/{qcsim_wheel}", f"files/wheels/{comm_wheel}"]
        },
    }


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(f"usage: {Path(__file__).name} <qcsim-wheel-name> <comm-wheel-name>", file=sys.stderr)
        return 2
    print(json.dumps(build_config(argv[0], argv[1]), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
