/**
 * The allowlist must equal the curriculum — in BOTH directions.
 *
 * This is what makes "no request path is ever stored" enforceable rather than
 * aspirational. If a notebook is added to the curriculum and not here, its
 * opens go silently uncounted; if a key lingers here after a notebook is
 * renamed, the table gains a column for something that no longer exists. Both
 * are build failures, not surprises found later in a DynamoDB scan.
 *
 * web/src/lib/content-manifest.json is generated by
 * scripts/validate_runnable.py --write-manifest and is the catalog's single
 * source of truth; template.test.mjs pins SiteHost to web/src/lib/site.ts the
 * same way, for the same reason.
 */
import { readFileSync } from "node:fs";
import test from "node:test";
import assert from "node:assert/strict";

import { NOTEBOOKS, SECTIONS, SECTION_SLUGS, sectionIndex } from "./curriculum.mjs";

const manifest = JSON.parse(
  readFileSync(new URL("../../web/src/lib/content-manifest.json", import.meta.url), "utf8"),
);

test("the sections are exactly the curriculum's, in curriculum order", () => {
  const declared = manifest.sections.map((s) => s.dirName);
  assert.deepEqual(SECTION_SLUGS, declared);
  assert.deepEqual([...SECTIONS].sort(), [...declared].sort());
  // Order is not decoration: furthestSection picks the maximum by this index.
  assert.equal(sectionIndex("00-prereqs"), 0);
  assert.ok(sectionIndex("06-hybrid-jobs") > sectionIndex("03-algorithms"));
  assert.equal(sectionIndex("not-a-section"), -1);
});

test("the notebooks are exactly the curriculum's, both directions", () => {
  const declared = new Set();
  for (const section of manifest.sections) {
    for (const nb of section.notebooks) {
      declared.add(`${section.dirName}/${nb.filename.replace(/\.ipynb$/, "")}`);
    }
  }
  const missing = [...declared].filter((k) => !NOTEBOOKS.has(k));
  const extra = [...NOTEBOOKS].filter((k) => !declared.has(k));
  assert.deepEqual(missing, [], "notebooks in the curriculum that this allowlist would not count");
  assert.deepEqual(extra, [], "keys here that no longer exist in the curriculum");
  assert.equal(NOTEBOOKS.size, declared.size);
});

test("every key names a section this file also declares", () => {
  for (const key of NOTEBOOKS) {
    const section = key.slice(0, key.indexOf("/"));
    assert.ok(SECTIONS.has(section), `${key} names a section that is not in SECTIONS`);
  }
});

test("curriculum.mjs is pure data — no fs, no network, no environment", () => {
  const src = readFileSync(new URL("./curriculum.mjs", import.meta.url), "utf8");
  assert.doesNotMatch(src, /process\.env|require\(|from "node:/);
});
