#!/usr/bin/env python3
"""Regenerate the committed cost-parity fixture from lib.utils.cost (the source of truth).

``web/src/components/quantum/__fixtures__/cost.json`` pins the Python pricing
table and a probe table of expected costs so the browser (TS ``cost.ts`` /
``hybrid.ts``) and Python (``lib/utils/cost.py``) estimators can never silently
diverge — the same two-sided lock as gates.json:

  - ``web/__tests__/components/quantum/cost.test.ts`` asserts the TS PRICING and
    estimateCost/qpuCost match this fixture   (catches TS-side drift).
  - ``tests/test_cost_fixture.py`` asserts this fixture still matches
    lib.utils.cost's live table                (catches Python-side drift).

Contract notes the fixture bakes in: costs are computed at exactly ONE task
(the TS side has a ``tasks`` multiplier the Python side does not), and the
per-minute branch ignores shots just as both implementations do.

Usage:
    .venv/bin/python scripts/gen_cost_fixture.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

# lib.utils.cost's table IS the source of truth this fixture pins; importing it
# directly (rather than redefining) is the whole point — the drift guard would
# be meaningless if it compared against a second copy.
from lib.utils.cost import PRICING, estimate_cost  # noqa: E402

# Probe points the TS test re-evaluates estimateCost at (tasks=1). Shots probes
# exercise the per-shot branch (30 is IonQ's task-fee/shot-rate crossover, a
# nicely non-trivial point); minutes probes exercise the per-minute branch.
SHOTS_PROBES = [1, 30, 1000, 12345]
MINUTES_PROBES = [0.0, 1.0, 7.5, 60.0]

FIXTURE_PATH = REPO_ROOT / "web/src/components/quantum/__fixtures__/cost.json"

_COMMENT = (
    "Generated by scripts/gen_cost_fixture.py from lib/utils/cost.py (single source of "
    "truth for Braket pricing). Do not edit by hand. 'pricing' is the raw table "
    "(snake_case, as in Python); 'expected' is estimate_cost() evaluated at the probe "
    "points, ONE task. web/__tests__/components/quantum/cost.test.ts asserts the TS "
    "PRICING + estimateCost + hybrid.qpuCost match (TS drift); tests/test_cost_fixture.py "
    "asserts this file still matches lib.utils.cost (Python drift), so "
    "cost.py <-> cost.json <-> cost.ts is locked on both sides."
)


def build_fixture() -> dict:
    """Build the fixture dict from lib.utils.cost's live table (the source of truth)."""
    expected = []
    for provider, rates in PRICING.items():
        if "per_shot" in rates:
            for shots in SHOTS_PROBES:
                expected.append(
                    {
                        "provider": provider,
                        "shots": shots,
                        "minutes": 0.0,
                        "cost": estimate_cost(provider, shots=shots, estimated_minutes=0.0),
                    }
                )
        else:
            for minutes in MINUTES_PROBES:
                expected.append(
                    {
                        "provider": provider,
                        "shots": 1000,
                        "minutes": minutes,
                        "cost": estimate_cost(provider, shots=1000, estimated_minutes=minutes),
                    }
                )
    return {"_comment": _COMMENT, "pricing": PRICING, "expected": expected}


def main() -> None:
    FIXTURE_PATH.write_text(json.dumps(build_fixture(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
