#!/usr/bin/env python3
"""Generate the committed H2 dissociation-curve fixture for the web widgets.

The quantum-chemistry web widgets (qham, qvqe, qpes) must show REAL numbers, not
invented coefficients that merely look chemical. Running PySCF/OpenFermion in the
browser is impossible (static export, no Python), so we precompute everything here
from PennyLane's differentiable Hartree-Fock (no PySCF dependency) and commit the
result as JSON. The widgets read this single file, so they can never disagree.

For each bond length R (angstrom) the fixture records, in STO-3G minimal basis:
  - jw:  the 15 Jordan-Wigner Pauli coefficients on 4 qubits, aligned to the
         module-level `jwTerms` ordering. Strings are BIG-ENDIAN (char k acts on
         qubit k, qubit 0 = leftmost) to match web/src/components/quantum/math.ts
         and qcsim.
  - c0,cz,cx: the Z2 symmetry-tapered single-qubit Hamiltonian H = c0 I + cz Z + cx X.
  - fci: lowest eigenvalue of the full 4-qubit JW Hamiltonian (STO-3G "FCI").
  - hf:  the restricted Hartree-Fock energy = <1100|H|1100> (HF determinant).

Sanity pinned by web tests: at R=0.74 the tapered ground energy
c0 - hypot(cz, cx) == fci == -1.1373 Ha (to chemical accuracy).

Usage:
    .venv/bin/python scripts/gen_h2_fixture.py
Writes web/src/components/quantum/__fixtures__/h2_dissociation.json.
"""
from __future__ import annotations

import json
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import numpy as np
import pennylane as qml

ANG2BOHR = 1.8897259886
HF_INDEX = int("1100", 2)  # H2 Hartree-Fock determinant in JW occupation order


def _pauli_string(op, n: int) -> str:
    """Canonical big-endian Pauli string of length n for a PennyLane operator.

    Char k is the single-qubit factor on qubit k (qubit 0 leftmost); 'I' if the
    operator does not act on that wire. Matches math.ts basisLabel convention.
    """
    factors = ["I"] * n
    # Decompose a tensor/word operator into its single-qubit Pauli factors.
    pauli_rep = op.pauli_rep
    if pauli_rep is not None:
        (word,) = [w for w in pauli_rep.keys()]  # single Pauli word (coeff stripped)
        for wire, p in word.items():
            factors[int(wire)] = p  # p is 'X' | 'Y' | 'Z'
    return "".join(factors)


def h2_hamiltonian(r_ang: float):
    r = r_ang * ANG2BOHR
    coords = np.array([[0.0, 0.0, 0.0], [0.0, 0.0, r]])
    H, n = qml.qchem.molecular_hamiltonian(["H", "H"], coords, basis="sto-3g")
    return H, n


def tapered_coeffs(H, n: int) -> tuple[float, float, float]:
    """Z2-taper the 4-qubit H2 Hamiltonian to one qubit; return (c0, cz, cx)."""
    gens = qml.symmetry_generators(H)
    paulixops = qml.paulix_ops(gens, n)
    sector = qml.qchem.optimal_sector(H, gens, 2)  # 2 active electrons
    Ht = qml.simplify(qml.taper(H, gens, paulixops, sector))
    c0 = cz = cx = 0.0
    for coeff, op in zip(*Ht.terms()):
        s = str(op)
        if s == "I()" or "Identity" in s:
            c0 += float(coeff)
        elif s.startswith("Z"):
            cz += float(coeff)
        elif s.startswith("X"):
            cx += float(coeff)
        else:
            raise ValueError(f"unexpected tapered term {s!r}")
    return c0, cz, cx


def main() -> None:
    grid = np.round(np.arange(0.30, 2.71, 0.05), 2)

    # Establish a stable, canonical ordering of the 15 Pauli strings from the
    # equilibrium Hamiltonian (the term set is geometry-independent).
    H_eq, n = h2_hamiltonian(0.75)
    term_order = sorted({_pauli_string(op, n) for op in H_eq.terms()[1]})

    points = []
    for r in grid:
        H, n = h2_hamiltonian(float(r))
        coeffs, ops = H.terms()
        by_string: dict[str, float] = {}
        for c, o in zip(coeffs, ops):
            by_string[_pauli_string(o, n)] = float(c)
        jw = [round(by_string.get(s, 0.0), 8) for s in term_order]

        M = qml.matrix(H, wire_order=list(range(n))).real
        fci = float(np.linalg.eigvalsh(M)[0])
        hf = float(M[HF_INDEX, HF_INDEX])
        c0, cz, cx = tapered_coeffs(H, n)

        points.append(
            {
                "R": float(r),
                "c0": round(c0, 6),
                "cz": round(cz, 6),
                "cx": round(cx, 6),
                "fci": round(fci, 6),
                "hf": round(hf, 6),
                "jw": jw,
            }
        )

    # Verify the honesty invariant before writing.
    eqm = min(points, key=lambda p: p["fci"])
    e0 = eqm["c0"] - float(np.hypot(eqm["cz"], eqm["cx"]))
    assert abs(e0 - eqm["fci"]) < 1e-6, (e0, eqm["fci"])
    assert abs(eqm["fci"] - (-1.1373)) < 2e-3, eqm["fci"]

    fixture = {
        "molecule": "H2",
        "basis": "sto-3g",
        "provenance": (
            "Generated by scripts/gen_h2_fixture.py using PennyLane differentiable "
            "Hartree-Fock (no PySCF). jw = 15 Jordan-Wigner coefficients (big-endian, "
            "qubit 0 leftmost) aligned to jwTerms; c0/cz/cx = Z2 symmetry-tapered "
            "single-qubit Hamiltonian; fci = lowest eigenvalue of the 4-qubit JW "
            "Hamiltonian (STO-3G); hf = <1100|H|1100> restricted Hartree-Fock energy. "
            "Energies in Hartree."
        ),
        "jwTerms": term_order,
        "equilibrium": {"R": eqm["R"], "fci": eqm["fci"], "hf": eqm["hf"]},
        "points": points,
    }

    out = (
        Path(__file__).resolve().parent.parent
        / "web/src/components/quantum/__fixtures__/h2_dissociation.json"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"wrote {out}")
    print(f"  points={len(points)}  jwTerms={len(term_order)}")
    print(f"  equilibrium R={eqm['R']} A  FCI={eqm['fci']}  HF={eqm['hf']}")
    print(f"  E0 from taper = {e0:.6f} Ha (invariant ok)")


if __name__ == "__main__":
    main()
