#!/usr/bin/env python3
"""Regenerate the committed IQP state-vector fixture from the Python encoder.

``web/src/components/quantum/__fixtures__/iqp-states.json`` pins the exact
states ``lib.ml.feature_maps.iqp_encoding`` prepares at a handful of feature
points. Two tests guard it from opposite sides so the browser widget
(``encoding.ts``'s ``iqpState``) and the Python library can never silently
diverge again — the 2026-08-18 audit found them implementing two different
unitaries under the same "IQP" name (fidelity 0.746 at the GUIDE's own worked
point), with the widget on the Havlicek angle convention and the library on the
simplified product convention the curriculum actually teaches:

  - ``web/__tests__/components/quantum/encoding.test.ts`` asserts ``iqpState``
    matches this fixture to 1e-10          (catches TS-side drift).
  - ``tests/test_feature_maps.py`` asserts the fixture still matches
    ``iqp_encoding``'s live statevectors   (catches Python-side drift).

The points are chosen so every plausible convention drift breaks at least one:
the GUIDE's worked point (0.6, 0.9) at reps 1 and 2, a signed pair, and an
equal pair at reps 3. A 2x angle factor, a (pi - x) shift, a swapped product
sign, or a dropped rep all change these amplitudes.

Usage:
    .venv/bin/python scripts/gen_iqp_fixture.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from lib.ml.feature_maps import iqp_encoding
from lib.utils.statevector import statevector

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = (
    REPO_ROOT / "web" / "src" / "components" / "quantum" / "__fixtures__" / "iqp-states.json"
)

# (features, reps) — 2-feature points only, because the widget is 2-qubit.
POINTS: list[tuple[list[float], int]] = [
    ([0.6, 0.9], 1),
    ([0.6, 0.9], 2),
    ([0.7, -1.1], 2),
    ([1.0, 1.0], 3),
]


def build_fixture() -> dict:
    cases = []
    for features, reps in POINTS:
        sv = statevector(iqp_encoding(np.array(features), reps=reps))
        cases.append(
            {
                "x": features,
                "reps": reps,
                "state": [[float(a.real), float(a.imag)] for a in sv],
            }
        )
    return {
        "_comment": (
            "Generated by scripts/gen_iqp_fixture.py from "
            "lib.ml.feature_maps.iqp_encoding (the canonical IQP convention: "
            "phi_i = x_i, phi_ij = x_i*x_j). Do not edit by hand. Each state is "
            "a list of [real, imag] amplitude pairs in Braket's big-endian "
            "basis order. encoding.test.ts asserts iqpState matches these to "
            "1e-10 (TS drift); tests/test_feature_maps.py asserts they still "
            "match the live Python statevectors (Python drift), so "
            "iqp_encoding <-> fixture <-> iqpState is locked on both sides."
        ),
        "cases": cases,
    }


if __name__ == "__main__":
    FIXTURE_PATH.write_text(json.dumps(build_fixture(), indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {FIXTURE_PATH.relative_to(REPO_ROOT)}")
