#!/usr/bin/env python3
"""Regenerate the committed gate-matrix fixture from qcsim's live matrices.

``web/src/components/quantum/__fixtures__/gates.json`` pins qcsim's exact gate
matrices. Two tests guard it from opposite sides so the browser (TS ``math.ts``)
and Python (``qcsim``) simulators can never silently diverge:

  - ``web/__tests__/components/quantum/math.test.ts`` asserts the TS kernel
    matches this fixture to 1e-10  (catches TS-side drift).
  - ``tests/test_gate_fixture.py`` asserts this fixture still matches qcsim's
    live matrices                   (catches qcsim/Python-side drift).

Because the fixture was previously "generated once" with no script, a change to
a qcsim gate matrix would leave the snapshot stale and the divergence invisible.
This script closes that gap: it reads qcsim's matrices directly (the single
source of truth) and rewrites the fixture. Run it whenever a qcsim gate matrix
changes, and commit the result.

Usage:
    .venv/bin/python scripts/gen_gate_fixture.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

# qcsim's private module-level matrices ARE the source of truth this fixture
# pins; importing them directly (rather than redefining) is the whole point —
# the drift guard would be meaningless if it compared against a second copy.
from qcsim.circuits import (
    _CNOT,
    _CZ,
    _H,
    _I,
    _S,
    _SWAP,
    _T,
    _X,
    _Y,
    _Z,
    _rx,
    _ry,
    _rz,
)

# Rotation angles the TS test evaluates rx/ry/rz at. Keys MUST match the `angles`
# table in web/__tests__/components/quantum/math.test.ts (same IEEE doubles).
ROTATION_ANGLES: list[tuple[str, float]] = [
    ("0", 0.0),
    ("pi_4", np.pi / 4),
    ("pi_3", np.pi / 3),
    ("pi_2", np.pi / 2),
    ("t0_9", 0.9),
    ("pi", np.pi),
]

FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent / "web/src/components/quantum/__fixtures__/gates.json"
)

_COMMENT = (
    "Generated by scripts/gen_gate_fixture.py from qcsim/src/qcsim/circuits.py gate "
    "matrices. Do not edit by hand. Each entry is a matrix of [real, imag] pairs. "
    "web/__tests__/components/quantum/math.test.ts asserts the TS kernel matches these "
    "to 1e-10 (TS drift); tests/test_gate_fixture.py asserts they still match qcsim's "
    "live matrices (qcsim drift), so qcsim <-> fixture <-> math.ts is locked on both "
    "sides. The 'rotations' section is _rx/_ry/_rz evaluated at fixed thetas (keys "
    "mirrored in the test)."
)


def _matrix(m: np.ndarray) -> list:
    """Serialize a complex matrix as rows of ``[real, imag]`` pairs — qcsim's exact doubles."""
    return [[[float(v.real), float(v.imag)] for v in row] for row in m]


def build_fixture() -> dict:
    """Build the fixture dict from qcsim's live gate matrices (the single source of truth)."""
    gates = {
        "I": _matrix(_I),
        "X": _matrix(_X),
        "Y": _matrix(_Y),
        "Z": _matrix(_Z),
        "H": _matrix(_H),
        "S": _matrix(_S),
        "T": _matrix(_T),
        "CNOT": _matrix(_CNOT),
        "CZ": _matrix(_CZ),
        "SWAP": _matrix(_SWAP),
    }
    rotations = {
        name: {key: _matrix(fn(theta)) for key, theta in ROTATION_ANGLES}
        for name, fn in (("rx", _rx), ("ry", _ry), ("rz", _rz))
    }
    return {"_comment": _COMMENT, "gates": gates, "rotations": rotations}


def main() -> None:
    FIXTURE_PATH.write_text(json.dumps(build_fixture(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
