#!/usr/bin/env python3
"""Regenerate the committed gate-matrix fixture from qcsim's live matrices.

``web/src/components/quantum/__fixtures__/gates.json`` pins qcsim's exact gate
matrices. Two tests guard it from opposite sides so the browser (TS ``math.ts``)
and Python (``qcsim``) simulators can never silently diverge:

  - ``web/__tests__/components/quantum/math.test.ts`` asserts the TS kernel
    matches this fixture to 1e-10  (catches TS-side drift).
  - ``tests/test_gate_fixture.py`` asserts this fixture still matches qcsim's
    live matrices                   (catches qcsim/Python-side drift).

Because the fixture was previously "generated once" with no script, a change to
a qcsim gate matrix would leave the snapshot stale and the divergence invisible.
This script closes that gap: it reads qcsim's matrices directly (the single
source of truth) and rewrites the fixture. Run it whenever a qcsim gate matrix
changes, and commit the result.

Completeness is STRUCTURAL, not hand-maintained. The gate list is derived from
``qcsim.circuits._GATE_SPECS``, so every gate qcsim registers is pinned. It used
to be a hardcoded list of ten, which silently omitted CCNOT and CPhaseShift —
the gates 02-grovers-search, 03-qft and 04-qpe are built on — while this
docstring and tests/test_gate_fixture.py both claimed full coverage. A hardcoded
list can only ever be self-consistent, so it could not notice its own gap.

Note this fixture is a qcsim-side drift snapshot, NOT a strict mirror of
``web/src/components/quantum/math.ts``: math.ts implements only I/X/Y/Z/H/S/T
plus a CNOT path, so CZ, SWAP, CCNOT and the controlled-phase entries are pinned
here with no TypeScript counterpart. math.test.ts names the keys it checks, so
extra entries are inert on the TS side.

Usage:
    .venv/bin/python scripts/gen_gate_fixture.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

# qcsim's gate registry IS the source of truth this fixture pins; reading it
# directly (rather than redefining or re-listing) is the whole point — the drift
# guard would be meaningless if it compared against a second copy, and a second
# LIST is how the two missing gates went unnoticed.
from qcsim.circuits import _GATE_SPECS

# Rotation angles the TS test evaluates rx/ry/rz at. Keys MUST match the `angles`
# table in web/__tests__/components/quantum/math.test.ts (same IEEE doubles).
ROTATION_ANGLES: list[tuple[str, float]] = [
    ("0", 0.0),
    ("pi_4", np.pi / 4),
    ("pi_3", np.pi / 3),
    ("pi_2", np.pi / 2),
    ("t0_9", 0.9),
    ("pi", np.pi),
]

FIXTURE_PATH = (
    Path(__file__).resolve().parent.parent / "web/src/components/quantum/__fixtures__/gates.json"
)

_COMMENT = (
    "Generated by scripts/gen_gate_fixture.py from qcsim/src/qcsim/circuits.py's "
    "_GATE_SPECS registry. Do not edit by hand. Each entry is a matrix of [real, imag] "
    "pairs. web/__tests__/components/quantum/math.test.ts asserts the TS kernel matches "
    "these to 1e-10 (TS drift); tests/test_gate_fixture.py asserts they still match "
    "qcsim's live matrices (qcsim drift), so qcsim <-> fixture <-> math.ts is locked on "
    "both sides. 'gates' holds every fixed matrix in the registry; 'rotations' holds "
    "every angle-parameterized one evaluated at fixed thetas (the rx/ry/rz keys are "
    "mirrored in the TS test). math.ts implements only a subset, so entries such as "
    "CZ, SWAP, CCNOT and cp have no TypeScript counterpart and are pinned qcsim-side "
    "only."
)


def _matrix(m: np.ndarray) -> list:
    """Serialize a complex matrix as rows of ``[real, imag]`` pairs — qcsim's exact doubles."""
    return [[[float(v.real), float(v.imag)] for v in row] for row in m]


def build_fixture() -> dict:
    """Build the fixture from qcsim's gate registry (the single source of truth).

    Derived, not listed: every ``_GATE_SPECS`` row lands in exactly one section,
    so a gate added to qcsim without regenerating this file fails
    ``tests/test_gate_fixture.py`` instead of quietly going unpinned.
    """
    gates: dict[str, list] = {}
    rotations: dict[str, dict[str, list]] = {}
    for key, spec in _GATE_SPECS.items():
        if callable(spec.matrix):
            # Angle-parameterized: pin it at each fixed theta. Lowercased so the
            # rx/ry/rz keys stay exactly what math.test.ts reads.
            rotations[key.lower()] = {
                angle_key: _matrix(spec.matrix(theta)) for angle_key, theta in ROTATION_ANGLES
            }
        else:
            gates[key] = _matrix(spec.matrix)
    return {"_comment": _COMMENT, "gates": gates, "rotations": rotations}


def main() -> None:
    FIXTURE_PATH.write_text(json.dumps(build_fixture(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
