/**
 * "Ask the margin" lesson tutor — a response-streaming Lambda behind a Function
 * URL. It grounds a Claude answer (Amazon Bedrock, ConverseStream) in the single
 * lesson the learner is reading, refuses anything outside it, and never invents
 * Braket/PennyLane APIs.
 *
 * The prompt/grounding logic MIRRORS web/src/lib/tutor.ts (the tested canonical) —
 * keep them in sync. corpus.json is generated by scripts/build_tutor_corpus.mjs.
 *
 * `awslambda` is a global provided by the Lambda Node runtime when response
 * streaming is enabled (InvokeMode: RESPONSE_STREAM on the Function URL).
 */
import { readFileSync } from "node:fs";
import { BedrockRuntimeClient, ConverseStreamCommand } from "@aws-sdk/client-bedrock-runtime";

const CORPUS = JSON.parse(readFileSync(new URL("./corpus.json", import.meta.url), "utf8"));
const client = new BedrockRuntimeClient({});

const OUT_OF_SCOPE_MESSAGE =
  "I can only help with the lessons in this curriculum. Open a lesson and ask me about it there.";

// In-band failure marker — MIRROR of web/src/lib/tutor.ts TUTOR_ERROR_SENTINEL
// (keep byte-identical). The response is already committed as HTTP 200, so the
// client scans for this to enter its error state rather than rendering the
// apology as part of the answer.
const TUTOR_ERROR_SENTINEL = "<<TUTOR-STREAM-ERROR>>";

// --- mirror of web/src/lib/tutor.ts buildSystemPrompt ---------------------
function buildSystemPrompt(section) {
  const headings = section.headings?.length
    ? `\nThe lesson covers these sections: ${section.headings.join("; ")}.`
    : "";
  return [
    `You are a tutor embedded in a single lesson of an Amazon Braket quantum-computing curriculum.`,
    `The lesson is titled "${section.title}".${headings}`,
    ``,
    `RULES:`,
    `- Answer ONLY using the lesson text provided below. If the question is outside this lesson, say so plainly and point the learner back to the relevant part of the curriculum.`,
    `- NEVER invent or guess Amazon Braket, PennyLane, or Qiskit APIs, method names, parameters, prices, or numbers. If you are not certain from the lesson text, say you are not sure.`,
    `- Prefer asking ONE short guiding question before giving the full answer (Socratic tutoring), then answer if the learner is still stuck.`,
    `- Be concise and concrete. Use the lesson's own notation. Do not use emojis.`,
    ``,
    `LESSON TEXT:`,
    section.text,
  ].join("\n");
}
// --------------------------------------------------------------------------

// A legit request is tiny ({slug, question<=2000 chars}); reject anything larger
// before decoding/parsing so a public, unauthenticated URL can't be made to burn
// CPU/memory JSON-parsing a multi-MB body per invocation.
const MAX_BODY_BYTES = 16 * 1024;

function parseBody(event) {
  if (!event?.body) return {};
  if (event.body.length > MAX_BODY_BYTES) return {};
  const raw = event.isBase64Encoded ? Buffer.from(event.body, "base64").toString("utf8") : event.body;
  try {
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

export const handler = awslambda.streamifyResponse(async (event, responseStream) => {
  const stream = awslambda.HttpResponseStream.from(responseStream, {
    statusCode: 200,
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });

  try {
    const body = parseBody(event);
    const slug = String(body.slug || "").slice(0, 64);
    const question = String(body.question || "").trim().slice(0, 2000);
    // Own-property lookup: a plain object inherits keys like "__proto__",
    // "constructor", and "toString", which would otherwise resolve to a truthy
    // (but text-less) value and slip past the grounding guard into a paid,
    // effectively ungrounded model call.
    const section = Object.prototype.hasOwnProperty.call(CORPUS, slug) ? CORPUS[slug] : undefined;

    if (!section || !question) {
      stream.write(OUT_OF_SCOPE_MESSAGE);
      stream.end();
      return;
    }

    const command = new ConverseStreamCommand({
      modelId: process.env.TUTOR_MODEL_ID,
      system: [{ text: buildSystemPrompt(section) }],
      messages: [{ role: "user", content: [{ text: question }] }],
      inferenceConfig: { maxTokens: 800, temperature: 0.2 },
    });

    const response = await client.send(command);
    for await (const item of response.stream) {
      const text = item.contentBlockDelta?.delta?.text;
      if (text) stream.write(text);
    }
    stream.end();
  } catch (err) {
    // Structured log so a CloudWatch metric filter can alarm on tutor failures —
    // the streamed response is already committed as 200, so neither the HTTP
    // status nor the Lambda Errors metric ever signals this on its own.
    console.error(JSON.stringify({ tutorError: true, name: err?.name, message: err?.message }));
    // In-band sentinel so the client enters its error state instead of rendering
    // the apology as part of the answer.
    stream.write(`${TUTOR_ERROR_SENTINEL}The tutor hit an error. Please try again.`);
    stream.end();
  }
});
