/**
 * "Ask the margin" lesson tutor — a response-streaming Lambda behind a Function
 * URL. It grounds a Claude answer in the single lesson the learner is reading,
 * refuses anything outside it, and never invents Braket/PennyLane APIs.
 *
 * PROVIDER, 2026-08-17: Anthropic's first-party Messages API, not Amazon
 * Bedrock. Bedrock never entitled this account to the paid models — sonnet-5,
 * opus-5 and fable-5 all answered `converse` with "not available for this
 * account ... contact AWS Sales", while `get-foundation-model-availability`
 * simultaneously reported them AUTHORIZED. Only haiku-4-5 was invocable, so
 * every tier above free was unreachable on the old provider.
 *
 * The prompt/grounding logic is imported from ./tutor-core.mjs (the single
 * source of truth, shared with web/src/lib/tutor.ts and the corpus builder).
 * corpus.json is generated by scripts/build_tutor_corpus.mjs.
 *
 * The per-request logic lives in `createHandlerCore` with its dependencies
 * (Anthropic client, corpus) injected, so it can be unit-tested
 * (lambda/tutor/index.test.mjs) without the Lambda runtime, a real model call,
 * or a packaged corpus. The production `handler` wires the real dependencies
 * through the `awslambda` streaming wrapper.
 *
 * `awslambda` is a global provided by the Lambda Node runtime when response
 * streaming is enabled (InvokeMode: RESPONSE_STREAM on the Function URL).
 */
import { readFileSync } from "node:fs";
import Anthropic from "@anthropic-ai/sdk";
import {
  DynamoDBClient,
  GetItemCommand,
  UpdateItemCommand,
} from "@aws-sdk/client-dynamodb";
import { SecretsManagerClient, GetSecretValueCommand } from "@aws-sdk/client-secrets-manager";
import { CognitoJwtVerifier } from "aws-jwt-verify";
import {
  buildSystemPrompt,
  MAX_QUESTION_CHARS,
  OUT_OF_SCOPE_MESSAGE,
  TUTOR_ERROR_SENTINEL,
  TUTOR_META_SENTINEL,
} from "./tutor-core.mjs";
import {
  ROSTER,
  MODEL_IDS,
  MODEL_LABELS,
  MAX_OUTPUT_TOKENS,
  USAGE_SHAPE_UNRECOGNIZED,
  isAllowed,
  modelRequestOptions,
  readUsage,
  creditsForUsage,
  maxCreditsFor,
  estimateTokens,
} from "./tutor-billing.mjs";

// Re-exported so a CloudWatch metric filter and the handler test can both bind
// to the same literal.
export { USAGE_SHAPE_UNRECOGNIZED };

// Re-exported so the handler test can assert the exact streamed strings.
export { OUT_OF_SCOPE_MESSAGE, TUTOR_ERROR_SENTINEL };

// In-band refusal messages for the metered path (client renders the text after
// the error sentinel as its error state). Exact strings are part of the wire
// contract — the panel matches on them to choose the right call to action.
export const SIGN_IN_REQUIRED_MESSAGE =
  "Sign in to use this tutor model. Your session may have expired — sign in again and retry.";
export const NOT_IN_PLAN_MESSAGE =
  "That tutor model isn't part of your plan. Choose an included model, or upgrade on the Pricing page.";
export const INSUFFICIENT_CREDITS_MESSAGE =
  "Not enough credits for this model. Nothing was generated and no credits were taken — top up on the Pricing page, or use an included model.";
export const METERING_UNAVAILABLE_MESSAGE =
  "Premium tutor models aren't available right now. The included model still works.";

/** Pinned log line for a wallet deployed WITHOUT a usable rate factor. Emitted
 *  once per cold start so the misconfiguration is alarmable (a metric filter
 *  can match this literal), because its runtime symptom — paid models refusing
 *  — is indistinguishable from metering being off on purpose. Never logs the
 *  offending value: a fat-fingered real factor is still the spread (rule 6). */
export const RATE_CARD_INVALID =
  "tutor: rate card missing or invalid; paid tutor disabled";

// corpus.json is generated by scripts/build_tutor_corpus.mjs and packaged at
// deploy time. Guard the read so importing this module in a test (where the
// gitignored corpus.json may be absent) never throws; production always ships it.
let CORPUS;
try {
  CORPUS = JSON.parse(readFileSync(new URL("./corpus.json", import.meta.url), "utf8"));
} catch (err) {
  // Structured warn (mirrors the error-path log below) so a deploy that forgot to
  // run build_tutor_corpus is visible in CloudWatch — otherwise an empty corpus
  // silently answers OUT_OF_SCOPE to every learner. (Absent in tests, which inject
  // their own fixture corpus; production always packages corpus.json.)
  console.warn(JSON.stringify({ tutorCorpusMissing: true, message: err?.message }));
  CORPUS = {};
}

// A legit request is tiny ({slug, question<=MAX_QUESTION_CHARS}); reject anything
// larger before decoding/parsing so a public, unauthenticated URL can't be made to
// burn CPU/memory JSON-parsing a multi-MB body per invocation.
const MAX_BODY_BYTES = 16 * 1024;

/**
 * Bound the model stream well under the function's own Timeout (60s). Without
 * this, a stalled model stream runs until the RUNTIME kills the process — and a
 * process kill never runs the catch below, so the in-band sentinel (the only
 * failure channel once the response is committed as 200) is never written and the
 * client renders whatever partial text arrived as a finished, authoritative
 * answer. 45s leaves headroom for the write-and-end after the throw.
 */
const STREAM_DEADLINE_MS = 45_000;

/** Distinct from `{}`: an over-cap body is a length problem, not an unknown lesson. */
const BODY_TOO_LARGE = Symbol("bodyTooLarge");

/**
 * What an over-cap body gets. It used to share OUT_OF_SCOPE_MESSAGE with the
 * unknown-slug and empty-question paths, which told a learner sitting inside the
 * lesson she just asked about that her question was off-topic — a false statement
 * about the request, with no way to discover the real cause.
 */
export const TOO_LONG_MESSAGE =
  "That question is too long for me to read. Trim it to the key part and ask again.";

function parseBody(event) {
  if (!event?.body) return {};
  // Byte length of the wire body, not string length. `event.body.length` counts
  // UTF-16 code units on a raw body (so a body of 3-byte math glyphs passed at up
  // to ~48 KiB) and base64 characters on an encoded one — neither is bytes, which
  // is what the constant names. Measured BEFORE base64-decoding on purpose: the
  // whole point of the gate is to not materialize a huge body.
  if (Buffer.byteLength(event.body, "utf8") > MAX_BODY_BYTES) return BODY_TOO_LARGE;
  const raw = event.isBase64Encoded ? Buffer.from(event.body, "base64").toString("utf8") : event.body;
  try {
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

/**
 * A promise that rejects once `ms` has elapsed, plus a `clear` to cancel it.
 * Racing every await against it turns a hung stream into a normal throw, which
 * the handler's catch can convert into the in-band sentinel — the failure path
 * that a runtime-level timeout kill can never reach.
 */
function deadlineGuard(ms) {
  let timer;
  const signal = new Promise((_resolve, reject) => {
    timer = setTimeout(() => reject(new Error(`tutor stream exceeded ${ms}ms`)), ms);
    // Never hold the event loop open on the guard alone.
    timer.unref?.();
  });
  return { signal, clear: () => clearTimeout(timer) };
}

/**
 * The per-request tutor logic with dependencies injected. `client` is anything
 * with `.messages.create(params)` resolving to an async-iterable of Anthropic
 * stream events; `corpus` maps slug -> { title, headings, text }. `stream` is
 * any `{ write(s), end() }` sink — the Lambda HttpResponseStream in prod, a fake
 * in tests. `deadlineMs` bounds the model stream (STREAM_DEADLINE_MS in prod;
 * a few ms in the deadline test). Resolves when the response has been fully
 * written. On any failure it writes the in-band TUTOR_ERROR_SENTINEL (the
 * response is already committed as 200).
 *
 * The per-generation output ceiling is MAX_OUTPUT_TOKENS[model], and the same
 * number feeds the pre-flight reserve below — they must not diverge or the
 * reserve stops being a bound and the overrun is absorbed rather than billed.
 */
export function createHandlerCore({
  client,
  corpus,
  deadlineMs = STREAM_DEADLINE_MS,
  // Metering deps — all optional, all injected (index wiring below builds
  // them from env). Absent = metering not deployed: the free path is untouched
  // and any explicit paid-model request is refused up front.
  verifier,
  wallet,
  // The factor that turns provider cost into the charged price. Its VALUE
  // lives in deployed configuration only (rule 6) — the wiring below reads it
  // from the environment; nothing in this repo carries it.
  rateFactor,
}) {
  // Metering is the PAIR (wallet, factor). A wallet without a usable factor
  // must never meter at raw provider cost — raw cost is a rate that differs
  // from every other surface (rule 5), and it would be invisible from outside.
  // It refuses exactly like no wallet at all, which charges nothing (rule 7 at
  // its strongest), and says so once per cold start so the misconfiguration is
  // alarmable rather than silently identical to metering-off-on-purpose.
  const factorUsable = Number.isFinite(rateFactor) && rateFactor > 0;
  if (wallet && !factorUsable) {
    console.error(JSON.stringify({ message: RATE_CARD_INVALID }));
  }
  const metering = wallet && factorUsable ? { wallet, factor: rateFactor } : undefined;
  return async (event, stream) => {
    // Billing state lives OUTSIDE the try so the catch can settle: a reserve
    // must be refunded down to real usage no matter how the stream ends.
    let model = "haiku-4-5";
    let reserved = 0;
    let usage = null;
    let sub = null;
    let settled = false;

    // Refund the reserve down to what the generation actually cost. Charged is
    // capped at the reserve (real input tokens can overshoot the char-based
    // estimate; the doctrine is fail-toward-undercharging, never a negative
    // refund that could push a wallet below zero). A failed refund is logged
    // loudly — it is bounded by one generation's worst case — rather than
    // failing a response that already streamed.
    const settle = async () => {
      if (!reserved || settled) return 0;
      settled = true;
      // A usage report we received but cannot read prices to zero, which is the
      // right direction (rule 7) but is indistinguishable in the logs from a
      // generation that genuinely cost nothing. That is how a provider field
      // rename becomes silent free inference: metering keeps reporting success
      // and billing nothing, forever, with no error anywhere. Say it out loud
      // so a metric filter can alarm, exactly as the billing Lambda alarms on
      // SIGNATURE_REJECTED. `usage === null` is the ordinary "stream died before
      // reporting" case and is not this.
      if (usage && !readUsage(usage)) {
        console.error(
          JSON.stringify({ message: USAGE_SHAPE_UNRECOGNIZED, model, keys: Object.keys(usage) })
        );
      }
      const charged = Math.min(creditsForUsage(model, usage, { factor: metering.factor }), reserved);
      const refund = reserved - charged;
      if (refund > 0) {
        try {
          await metering.wallet.credit(sub, refund);
        } catch (e) {
          console.error(
            JSON.stringify({ tutorRefundFailed: true, refund, name: e?.name, message: e?.message })
          );
        }
      }
      console.log(
        JSON.stringify({
          tutorSettle: true,
          sub,
          model,
          reservedCredits: reserved,
          chargedCredits: charged,
          refundedCredits: refund,
        })
      );
      return charged;
    };

    // In-band refusal: the response is already committed as 200, so a refusal
    // is the error sentinel plus an exact, client-matchable message.
    const refuse = (message) => {
      stream.write(`${TUTOR_ERROR_SENTINEL}${message}`);
      stream.end();
    };

    try {
      const body = parseBody(event);
      if (body === BODY_TOO_LARGE) {
        stream.write(TOO_LONG_MESSAGE);
        stream.end();
        return;
      }
      const slug = String(body.slug || "").slice(0, 64);
      // Single-sourced with the panel's textarea maxLength (tutor-core.mjs), so
      // the browser stops the input at exactly the boundary this slices to
      // instead of letting a long paste be amputated mid-word and answered as
      // though it were the whole question.
      const question = String(body.question || "").trim().slice(0, MAX_QUESTION_CHARS);
      // Own-property lookup: a plain object inherits keys like "__proto__",
      // "constructor", and "toString", which would otherwise resolve to a truthy
      // (but text-less) value and slip past the grounding guard into a paid,
      // effectively ungrounded model call.
      const section = Object.prototype.hasOwnProperty.call(corpus, slug) ? corpus[slug] : undefined;

      if (!section || !question) {
        stream.write(OUT_OF_SCOPE_MESSAGE);
        stream.end();
        return;
      }

      // ---- Model selection + billing gate --------------------------------
      // Legacy requests ({slug, question}) take none of these branches and
      // behave byte-identically to the pre-metering handler. An explicit,
      // KNOWN, but unauthorized model is refused — never silently substituted:
      // serving Haiku to someone who asked for (and expected to pay for) Opus
      // is a mis-serve, not a graceful degrade. Unknown names fall through to
      // the default, since no shipped UI can send them.
      const requested = typeof body.model === "string" ? body.model : undefined;
      const wantsMeta = body.meta === true;
      let metered = false;
      if (requested && MODEL_IDS[requested]) {
        if (ROSTER.free.includes(requested)) {
          model = requested; // the funnel model: free for everyone, no auth
        } else {
          if (!metering) return refuse(METERING_UNAVAILABLE_MESSAGE);
          const token = event.headers?.["x-tutor-auth"];
          if (!token || !verifier) return refuse(SIGN_IN_REQUIRED_MESSAGE);
          try {
            sub = (await verifier.verify(token)).sub;
          } catch {
            return refuse(SIGN_IN_REQUIRED_MESSAGE);
          }
          const tier = await metering.wallet.readTier(sub);
          if (!isAllowed(tier, requested)) return refuse(NOT_IN_PLAN_MESSAGE);
          model = requested;
          metered = true;
        }
      }

      const systemText = buildSystemPrompt(section);

      // ---- Pre-flight reserve (paid models only) --------------------------
      // Debit the worst case BEFORE the model call — we cannot know real usage
      // until after the stream, and starting a generation the wallet cannot
      // cover means either eating the cost or clawing back after delivering.
      // `reserved` is set only after the debit COMMITS, so a refused debit can
      // never be "refunded" by the settle path.
      if (metered) {
        const need = maxCreditsFor(model, {
          inputTokens: estimateTokens(systemText.length + question.length),
          maxOutputTokens: MAX_OUTPUT_TOKENS[model],
          factor: metering.factor,
        });
        try {
          await metering.wallet.debit(sub, need);
          reserved = need;
          // The tutor was the ONLY wallet writer leaving no artifact: stripe
          // persists EVENT#/RECEIPT#, the QPU persists fundedBy +
          // creditsCharged on its task row, and this path did a bare
          // UpdateItem and logged only failures. With no DynamoDB stream on
          // the wallet, PITR gives restore, not history — so "40 credits
          // vanished" was unanswerable here alone. Two lines make it a Logs
          // Insights query, and a reserve with no matching settle is how you
          // find a stranded reservation (nothing sweeps those today).
          //
          // CREDITS ONLY, never a dollar figure: rule 6 keeps the cost basis
          // out of version control, and a log group is not the private notes.
          // No question text, no lesson text — this is a billing record.
          console.log(JSON.stringify({ tutorReserve: true, sub, model, reservedCredits: reserved }));
        } catch (err) {
          if (err?.name === "ConditionalCheckFailedException") {
            return refuse(INSUFFICIENT_CREDITS_MESSAGE);
          }
          throw err;
        }
      }

      const request = {
        model: MODEL_IDS[model],
        // Per-model: thinking mode and effort. Not one shape for all four —
        // every knob in there is a 400 on at least one roster model.
        ...modelRequestOptions(model),
        // Thinking bills as OUTPUT and counts against this same ceiling, which
        // is why it is per-model too: fable-5 cannot be told not to think.
        max_tokens: MAX_OUTPUT_TOKENS[model],
        // The lesson text is byte-identical for every question on a lesson, so it is a
        // perfect cache prefix. The breakpoint goes at the END of `system` — the API
        // renders tools -> system -> messages, so this caches everything stable and
        // leaves the learner's question (the only varying part) outside the prefix.
        //
        // MINIMUM CACHEABLE PREFIX, and note it is NOT monotonic across generations:
        // haiku-4-5 needs 4,096 tokens, sonnet-5 needs 1,024, opus-5 and fable-5 need
        // only 512. Under the minimum the request is accepted and simply does not
        // cache — no error, no warning, `cache_creation_input_tokens: 0`. The old
        // Bedrock-era note here said only 3 of our 7 lessons cleared the bar; that
        // was measured against Haiku's 4,096 and still holds for the free tier, but
        // every paid model now clears it on every lesson. Re-measure with
        // probe-tokens.mjs if lesson text shrinks.
        //
        // Do NOT interpolate anything per-request ahead of this point. A timestamp, a user
        // id, or a reordered heading list invalidates the prefix and silently restores full
        // input cost with no visible symptom.
        system: [{ type: "text", text: systemText, cache_control: { type: "ephemeral" } }],
        messages: [{ role: "user", content: question }],
        stream: true,
      };

      // Every await races the deadline, so both a request that never returns headers
      // and a stream that goes silent mid-answer surface as a throw here rather
      // than as a truncated body the client cannot distinguish from a finished one.
      const guard = deadlineGuard(deadlineMs);
      try {
        const response = await Promise.race([client.messages.create(request), guard.signal]);
        const events = response[Symbol.asyncIterator]();
        for (;;) {
          const next = await Promise.race([events.next(), guard.signal]);
          if (next.done) break;
          const ev = next.value;
          if (ev?.type === "content_block_delta" && ev.delta?.type === "text_delta") {
            stream.write(ev.delta.text);
          }
          // REAL usage, and it arrives in TWO events rather than one.
          // `message_start` carries the input legs (input_tokens plus the cache
          // read/creation counts); `message_delta` carries the final
          // output_tokens. Reading either alone silently undercharges: only the
          // input legs, and output is billed at zero; only the delta, and the
          // entire prompt — the expensive half on this workload — is free.
          // Merge, do not replace.
          if (ev?.type === "message_start" && ev.message?.usage) {
            usage = { ...ev.message.usage };
          } else if (ev?.type === "message_delta" && ev.usage) {
            usage = { ...usage, ...ev.usage };
          }
        }
      } finally {
        guard.clear();
      }

      const charged = await settle();
      if (wantsMeta) {
        // Trailer AFTER the answer: which model actually answered, what it
        // cost. Opt-in only, so pre-metering clients never see these bytes.
        stream.write(
          TUTOR_META_SENTINEL +
            JSON.stringify({ model, label: MODEL_LABELS[model], credits: charged })
        );
      }
      stream.end();
    } catch (err) {
      // A failed generation costs nothing: no usage was captured (or the
      // stream died before completing), so the settle refunds the reserve
      // down to whatever the provider actually reported — usually all of it.
      await settle();
      // Structured log so a CloudWatch metric filter can alarm on tutor failures —
      // the streamed response is already committed as 200, so neither the HTTP
      // status nor the Lambda Errors metric ever signals this on its own.
      console.error(JSON.stringify({ tutorError: true, name: err?.name, message: err?.message }));
      // In-band sentinel so the client enters its error state instead of rendering
      // the apology as part of the answer.
      stream.write(`${TUTOR_ERROR_SENTINEL}The tutor hit an error. Please try again.`);
      stream.end();
    }
  };
}

// `streamifyResponse` only exists on the `awslambda` global in the response-
// streaming Lambda runtime. We capability-check for the FUNCTION rather than
// for the global: some AWS SDK clients install their own `awslambda` global as
// an empty object, so a mere existence check has been insufficient before and
// could be again. Outside the Lambda runtime (e.g. `node --test`) it is absent,
// so the module loads cleanly (handler === undefined) and the test can import
// createHandlerCore. In production the real runtime provides it and the
// streaming handler is created.
//
// The core is built ONCE at module scope, matching lambda/qpu and lambda/sync
// (whose header says it mirrors this file's DI-core pattern). Note this is only
// possible because the credential is deferred to first model call; building the
// core would otherwise have to be async and every request would await it.
// ---- Metering wiring (env-gated, like every integration in this repo) ------
// WALLET_TABLE unset = no wallet: paid models refuse, the free path is exactly
// the pre-metering tutor. Same DynamoDB idiom as lambda/qpu's wallet legs:
// conditional debit that can neither go negative nor mint a phantom row, and
// an unconditional refund credit.
// Exported (with injectable deps) so the handler test can pin the DynamoDB
// shape of the credit leg without a live client; production calls it bare.
export function buildWallet({ table = process.env.WALLET_TABLE, ddb } = {}) {
  if (!table) return undefined;
  const client = ddb ?? new DynamoDBClient({});
  const key = (sub) => ({ pk: { S: `WALLET#${sub}` } });
  return {
    async readTier(sub) {
      const res = await client.send(new GetItemCommand({ TableName: table, Key: key(sub) }));
      return res.Item?.tier?.S ?? "free";
    },
    async debit(sub, n) {
      await client.send(
        new UpdateItemCommand({
          TableName: table,
          Key: key(sub),
          UpdateExpression: "ADD credits :neg",
          // The clawback clause enforces the product rule that a debt must be
          // CLEARED before spending resumes — same guard as the QPU debit, so
          // one reclaimed refund cannot be spent around via the other backend.
          ConditionExpression:
            "attribute_exists(pk) AND credits >= :need AND " +
            "(attribute_not_exists(clawbackOwedCredits) OR clawbackOwedCredits = :zero)",
          ExpressionAttributeValues: {
            ":neg": { N: String(-n) },
            ":need": { N: String(n) },
            ":zero": { N: "0" },
          },
        })
      );
    },
    async credit(sub, n) {
      try {
        await client.send(
          new UpdateItemCommand({
            TableName: table,
            Key: key(sub),
            UpdateExpression: "ADD credits :pos",
            // A refund must never MINT a wallet row (rule 11): an unconditional
            // ADD against a missing WALLET# key would materialize credits
            // nobody paid for. The debit above already requires the row, so a
            // refund against a missing one means it vanished mid-request.
            ConditionExpression: "attribute_exists(pk)",
            ExpressionAttributeValues: { ":pos": { N: String(n) } },
          })
        );
      } catch (e) {
        if (e?.name === "ConditionalCheckFailedException") {
          // Money owed a learner that cannot be delivered without minting.
          // Never throw on the refund path — the answer already streamed; the
          // loud structured line is the alarm hook (same idiom as
          // tutorRefundFailed in the settle path above).
          console.error(JSON.stringify({ tutorRefundNoWalletRow: true, sub, refund: n }));
          return;
        }
        throw e;
      }
    },
  };
}

// Cognito ID-token verification, in-Lambda: a streaming Function URL has no
// API Gateway authorizer to lean on, so the JWT is verified here against the
// pool's JWKS (aws-jwt-verify caches the keys across invocations). Env-gated:
// without pool config, paid models simply require sign-in and refuse.
function buildVerifier() {
  const userPoolId = process.env.USER_POOL_ID;
  const clientId = process.env.USER_POOL_CLIENT_ID;
  if (!userPoolId || !clientId) return undefined;
  return CognitoJwtVerifier.create({ userPoolId, clientId, tokenUse: "id" });
}

// ---- Provider credential --------------------------------------------------
// The Anthropic API key lives in ONE Secrets Manager secret ({ apiKey }), read
// with the function's own least-privilege execution role — the same shape
// lambda/stripe uses. Keeping it out of the environment entirely means it is
// never visible via GetFunctionConfiguration.
//
// It is fetched on FIRST MODEL CALL rather than at module load, for two
// reasons. Reading a secret is async, and awaiting it at module scope would put
// an AWS round trip in front of every request — including the ones that never
// reach the model at all: an unknown lesson slug, an over-long body, a refused
// paid-model request. And a rejection must never be memoized: a Secrets Manager
// throttle, or a read that races a rotation, should cost one invocation rather
// than poisoning a warm container for its whole life. That failure mode is not
// hypothetical in this repo — a rotated webhook secret once sat unread on warm
// containers for 24 straight invocations while every request quietly 400'd,
// with nothing in the logs to say so.
let keyed;
function anthropic() {
  if (!keyed) {
    keyed = (async () => {
      const sm = new SecretsManagerClient({});
      const secret = await sm.send(new GetSecretValueCommand({ SecretId: process.env.SECRET_ID }));
      return new Anthropic({ apiKey: JSON.parse(secret.SecretString).apiKey });
    })().catch((err) => {
      keyed = undefined;
      throw err;
    });
  }
  return keyed;
}

/** The `client` shape createHandlerCore expects, with the credential deferred
 *  to first use. Tests inject a plain object of the same shape. */
const client = {
  messages: { create: async (params) => (await anthropic()).messages.create(params) },
};

const core = createHandlerCore({
  client,
  corpus: CORPUS,
  verifier: buildVerifier(),
  wallet: buildWallet(),
  // RATE_CARD is injected at deploy time from Secrets Manager (template.yaml
  // resolves {{resolve:secretsmanager:...}} behind an !If), so the value never
  // exists in this repository. Number("") and Number(undefined) are both
  // unusable, which the core treats as metering OFF — refusal, never raw cost.
  rateFactor: Number(process.env.RATE_CARD),
});

export const handler =
  typeof awslambda !== "undefined" && typeof awslambda.streamifyResponse === "function"
    ? awslambda.streamifyResponse((event, responseStream) => {
        const stream = awslambda.HttpResponseStream.from(responseStream, {
          statusCode: 200,
          headers: { "Content-Type": "text/plain; charset=utf-8" },
        });
        return core(event, stream);
      })
    : undefined;
